### 멤버조회
GET localhost:8080/me
Accept: application/json

### 멤버조회
GET localhost:8080/me
Accept: text/csv


### 멤버생성
POST localhost:8080/members
Content-Type: application/json

{
  "name" : "신건영",
  "age" : 20,
  "class" : "A"
}